# config.yaml
defaults:
  - _self_

model_name: qtransformer
mode: both
use_wandb: True

model_config:
  state_dim: 39
  num_actions: 4  
  action_bins: 256
  depth: 1
  heads: 8
  dim_head: 64
  cond_drop_prob: 0.2
  dueling: True

training_config: 
    dataset: data/box-close-v2.npz
    save_model: True
    num_train_steps: 400
    learning_rate: 7e-4
    batch_size: 1
    grad_accum_every: 16
    binary_rewards: False
    test: False
    test_every: 500
        
test_config: 
    env_name: box-close-v2
    load_model: False
    render: True
    num_episodes: 5
    max_num_steps_per_episode: 500
        
