defaults:
  - _self_

wandb:
  model_name: qtransformer
  mode: test
  use_wandb: True

model:
  state_dim: 39
  action_dim: 4
  action_bins: 1024
  transformer_depth: 6
  heads: 8
  dim_head: 64
  dropout: 0.1
  learning_rate: 0.001
  weight_decay: 0.0

train:
  save_model: True
  batch_size: 32
  context_length: 15
  epochs: 5
  shuffle: True
  file: "metaworld/button-press-topdown-wall-v2.npz"
  model_path: "trafo.pth"
  ema_beta: 0.99
  ema_update_after_step: 10
  ema_update_every: 5
  discount_factor_gamma: 0.98
  conservative_reg_loss_weight: 1.0
  min_reward: 0.0
  max_grad_norm: 1.0
  monte_carlo_return: None
  binary_reward: True
  grad_accum_every: 16

test:
  load_model: True
  env_name: "button-press-topdown-wall-v2"
  model_path: "trafo_cp_0_accel.pth"
  render: True
  steps: 200
  episodes: 10
  

