defaults:
  - _self_

wandb:
  model_name: qtransformer
  mode: test
  use_wandb: True

model:
  state_dim: 39
  action_dim: 4
  num_bins: 1024
  transformer_layers: 2
  transformer_heads: 3
  learning_rate: 0.001

train:
  batch_size: 32
  epochs: 4
  epsilon: 0.1
  shuffle: False
  file: "metaworld/button-press-topdown-wall-v2.npz"
  model_path: "simple_net.pth"

test:
  load_model: True
  env_name: "button-press-topdown-wall-v2"
  model_path: "simple_net.pth"
  render: True
  steps: 10000
  

