defaults:
  - _self_

wandb:
  model_name: qtransformer
  mode: train
  use_wandb: True

model:
  state_dim: 39
  action_dim: 4
  num_bins: 1024
  transformer_layers: 2
  transformer_heads: 3
  learning_rate: 0.001

train:
  batch_size: 32
  epochs: 100
  epsilon: 0.1
  file: "data/button-press-topdown-wall-v2.npz"